import http from 'node:http';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { extname } from 'node:path';
import { all, one, run } from './db.js';
import { audit, auth, createSession, hashPassword, id, now, sha256, validPassword } from './auth.js';
import { analyseClaim, aiDefaults } from './analysis.js';
import { sendPasswordResetEmail } from './email.js';

const PORT = Number(process.env.PORT || 3000); const REQUIRED_ANGLES = ['front','back','left','right','top','damage_closeup'];
mkdirSync('uploads', { recursive: true });
const json = (res, status, data) => { res.writeHead(status, {'Content-Type':'application/json'}); res.end(JSON.stringify(data)); };
const readBody = req => new Promise((resolve,reject) => { let raw=''; req.on('data', c => { raw += c; if(raw.length > 15_000_000) reject(Error('Payload too large')); }); req.on('end',()=>{ try { resolve(raw ? JSON.parse(raw) : {}); } catch { reject(Error('Invalid JSON body')); } }); });
const requireUser = (req,res,role) => { const user = auth(req, role); if(!user) { json(res,401,{error: role ? `Officer ${role} access required` : 'Authentication required'}); return null; } return user; };
function claimForUser(claimId, user) { const claim = one('SELECT * FROM claims WHERE id = ?', claimId); return claim && (user.role === 'officer' || claim.user_id === user.id) ? claim : null; }
function parseImage(data) { const m = /^data:(image\/(?:jpeg|png|webp));base64,(.+)$/.exec(data || ''); if (!m) throw Error('Images must be JPEG, PNG or WebP data URLs.'); const buffer=Buffer.from(m[2],'base64'); if(buffer.length < 4_000) throw Error('Image is too small to analyse.'); if(buffer.length > 8_000_000) throw Error('Image exceeds 8MB limit.'); return {mime:m[1],buffer}; }

const server = http.createServer(async (req,res) => { try {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PATCH, OPTIONS');
  if (req.method === 'OPTIONS') { res.writeHead(204); return res.end(); }
  const url = new URL(req.url, `http://${req.headers.host}`); const path = url.pathname; const body = ['POST','PATCH'].includes(req.method) ? await readBody(req) : {};
  if (req.method === 'GET' && (path === '/' || path === '/index.html')) {
    res.writeHead(200, {'Content-Type':'text/html; charset=utf-8'});
    return res.end(readFileSync('index.html'));
  }
  if(req.method==='GET' && path==='/health') return json(res,200,{status:'ok'});
  if(req.method==='GET' && path==='/ai/configuration') return json(res,200,{provider:'OpenAI',supportedProviders:['openai'],defaultModel:aiDefaults.model,keyStorage:'The browser sends the supplied key only with an analysis request. The API does not persist it.'});
  if(req.method==='POST' && path==='/auth/register') { const {name,email,password,phone,officialLicence,role='customer'}=body; if(!name||!email||!password||password.length<8) return json(res,400,{error:'Name, valid email and 8+ character password required'}); if(!['customer','officer'].includes(role)) return json(res,400,{error:'Invalid role'}); if(one('SELECT id FROM users WHERE email = ?',email.toLowerCase())) return json(res,409,{error:'Email already registered'}); const user={id:id(),name,email:email.toLowerCase(),role,phone:phone||null,officialLicence:officialLicence||null}; run('INSERT INTO users VALUES (?, ?, ?, ?, ?, ?, ?, ?)',user.id,user.role,user.name,user.email,hashPassword(password),user.phone,user.officialLicence,now()); return json(res,201,{token:createSession(user),user:{...user,password:undefined}}); }
  if(req.method==='POST' && path==='/auth/login') { const user=one('SELECT * FROM users WHERE email = ?',String(body.email||'').toLowerCase()); if(!user||!validPassword(body.password||'',user.password_hash)) return json(res,401,{error:'Invalid email or password'}); return json(res,200,{token:createSession(user),user:{id:user.id,name:user.name,email:user.email,role:user.role}}); }
  if(req.method==='POST' && path==='/auth/forgot-password') { const user=one('SELECT id,email FROM users WHERE email=?',String(body.email||'').toLowerCase()); if(!user) return json(res,200,{message:'If that email is registered, a reset link has been sent.'}); run('DELETE FROM password_resets WHERE user_id=? OR expires_at < ?',user.id,now()); const token=id()+id(); const resetUrl=`${process.env.APP_URL||'http://localhost:3000'}/?reset=${token}`; run('INSERT INTO password_resets VALUES (?,?,?,?,?,?)',id(),user.id,sha256(Buffer.from(token)),new Date(Date.now()+60*60*1000).toISOString(),null,now()); const email=await sendPasswordResetEmail({to:user.email,resetUrl}); return json(res,200,{message:'If that email is registered, a reset link has been sent.',...(email.developmentUrl?{developmentResetUrl:email.developmentUrl}:{})}); }
  if(req.method==='POST' && path==='/auth/reset-password') { const {token,newPassword}=body; if(!token||!newPassword||newPassword.length<8)return json(res,400,{error:'A valid reset token and a password of at least 8 characters are required'}); const reset=one('SELECT * FROM password_resets WHERE token_hash=? AND used_at IS NULL AND expires_at > ?',sha256(Buffer.from(token)),now()); if(!reset)return json(res,400,{error:'This reset link is invalid or has expired. Request a new one.'}); run('UPDATE users SET password_hash=? WHERE id=?',hashPassword(newPassword),reset.user_id); run('UPDATE password_resets SET used_at=? WHERE id=?',now(),reset.id); run('DELETE FROM password_resets WHERE user_id=? AND id!=?',reset.user_id,reset.id); return json(res,200,{message:'Password updated. You can now sign in.'}); }
  if(req.method==='GET' && path==='/me') { const user=requireUser(req,res); if(!user)return; const vehicle=one('SELECT * FROM vehicles WHERE user_id=?',user.id); const policy=one('SELECT * FROM policies WHERE user_id=?',user.id); return json(res,200,{user,vehicle,policy}); }
  if(req.method==='PATCH' && path==='/me/details') { const user=requireUser(req,res); if(!user)return; const {phone,officialLicence,vehicle,insurance}=body; if(phone!==undefined||officialLicence!==undefined) run('UPDATE users SET phone=?, official_licence=? WHERE id=?',phone??user.phone,officialLicence??user.official_licence,user.id); if(vehicle){ if(!vehicle.make||!vehicle.model||!vehicle.numberPlate)return json(res,400,{error:'Vehicle make, model and numberPlate are required'}); const existing=one('SELECT id FROM vehicles WHERE user_id=?',user.id); const values=[vehicle.make,vehicle.model,vehicle.year||null,vehicle.numberPlate.toUpperCase(),vehicle.vin||null]; existing?run('UPDATE vehicles SET make=?,model=?,year=?,number_plate=?,vin=? WHERE id=?',...values,existing.id):run('INSERT INTO vehicles VALUES (?,?,?,?,?,?,?)',id(),user.id,...values); } if(insurance){ if(!insurance.provider||!insurance.policyNumber||!insurance.coverageType||!insurance.expiresOn)return json(res,400,{error:'Complete insurance information is required'}); const existing=one('SELECT id FROM policies WHERE user_id=?',user.id); const v=[insurance.provider,insurance.policyNumber,insurance.coverageType,insurance.expiresOn]; existing?run('UPDATE policies SET provider=?,policy_number=?,coverage_type=?,expires_on=? WHERE id=?',...v,existing.id):run('INSERT INTO policies VALUES (?,?,?,?,?,?)',id(),user.id,...v); } return json(res,200,{message:'Account details saved'}); }
  if(req.method==='POST' && path==='/claims') { const user=requireUser(req,res,'customer'); if(!user)return; const {incidentDescription,incidentDate,vehicleId,policyId}=body; const vehicle=vehicleId?one('SELECT * FROM vehicles WHERE id=? AND user_id=?',vehicleId,user.id):one('SELECT * FROM vehicles WHERE user_id=?',user.id); const policy=policyId?one('SELECT * FROM policies WHERE id=? AND user_id=?',policyId,user.id):one('SELECT * FROM policies WHERE user_id=?',user.id); if(!incidentDescription||!incidentDate||!vehicle||!policy)return json(res,400,{error:'Incident description/date plus saved vehicle and insurance details are required'}); const claim={id:id(),num:`VA-${Math.floor(1000+Math.random()*9000)}`,created:now()}; run('INSERT INTO claims VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)',claim.id,claim.num,user.id,vehicle.id,policy.id,incidentDescription,incidentDate,'draft',null,null,null,null,claim.created,claim.created); audit(claim.id,user.id,'claim_created'); return json(res,201,{claimId:claim.id,claimNumber:claim.num,status:'draft'}); }
  const imageMatch=path.match(/^\/claims\/([^/]+)\/images$/); if(req.method==='POST'&&imageMatch){ const user=requireUser(req,res);if(!user)return;const claim=claimForUser(imageMatch[1],user);if(!claim)return json(res,404,{error:'Claim not found'});const {angle,image}=body;if(!REQUIRED_ANGLES.includes(angle))return json(res,400,{error:`angle must be one of: ${REQUIRED_ANGLES.join(', ')}`});let file;try{file=parseImage(image)}catch(e){return json(res,400,{error:e.message})}const digest=sha256(file.buffer), extension=file.mime.split('/')[1], filePath=`uploads/${claim.id}-${angle}-${digest.slice(0,8)}.${extension}`;writeFileSync(filePath,file.buffer);const isValid=file.buffer.length>10_000;run('INSERT OR REPLACE INTO claim_images VALUES (?,?,?,?,?,?,?,?,?)',id(),claim.id,angle,filePath,digest,file.mime,file.buffer.length,isValid?1:0,isValid?'Valid image':'Image too low quality');audit(claim.id,user.id,'image_uploaded',angle);return json(res,201,{angle,isValid,validationNote:isValid?'Valid image':'Image too low quality'}); }
  const analyseMatch=path.match(/^\/claims\/([^/]+)\/analyse$/); if(req.method==='POST'&&analyseMatch){const user=requireUser(req,res,'customer');if(!user)return;const claim=claimForUser(analyseMatch[1],user);if(!claim)return json(res,404,{error:'Claim not found'});const images=all('SELECT angle,is_valid FROM claim_images WHERE claim_id=?',claim.id);const missing=REQUIRED_ANGLES.filter(a=>!images.some(i=>i.angle===a));if(missing.length)return json(res,400,{error:'All required views must be uploaded',missing});const result=await analyseClaim(claim.id,body.aiConfig);run('INSERT OR REPLACE INTO analyses VALUES (?,?,?,?,?,?,?)',id(),claim.id,JSON.stringify(result.damage),JSON.stringify(result.fraud),JSON.stringify(result.estimate),result.confidence,now());run('UPDATE claims SET status=?,updated_at=? WHERE id=?','analysed',now(),claim.id);audit(claim.id,user.id,'analysis_completed',`OpenAI model: ${result.ai.model}`);return json(res,200,result);}
  const submitMatch=path.match(/^\/claims\/([^/]+)\/submit$/);if(req.method==='POST'&&submitMatch){const user=requireUser(req,res,'customer');if(!user)return;const claim=claimForUser(submitMatch[1],user);if(!claim)return json(res,404,{error:'Claim not found'});if(!one('SELECT id FROM analyses WHERE claim_id=?',claim.id))return json(res,400,{error:'Run analysis and review results before submission'});run('UPDATE claims SET status=?,submitted_at=?,updated_at=? WHERE id=?','pending_officer_review',now(),now(),claim.id);audit(claim.id,user.id,'submitted_for_officer_review');return json(res,200,{message:'Claim sent to insurance officer',status:'pending_officer_review'});}
  if(req.method==='GET'&&path==='/officer/claims'){const officer=requireUser(req,res,'officer');if(!officer)return;const claims=all(`SELECT c.id,c.claim_number,c.status,c.incident_date,c.incident_description,u.name, v.make,v.model,v.number_plate,a.fraud_json,a.estimate_json FROM claims c JOIN users u ON u.id=c.user_id JOIN vehicles v ON v.id=c.vehicle_id LEFT JOIN analyses a ON a.claim_id=c.id WHERE c.status='pending_officer_review' ORDER BY c.submitted_at`);return json(res,200,{claims:claims.map(c=>({...c,fraud:JSON.parse(c.fraud_json),estimate:JSON.parse(c.estimate_json),fraud_json:undefined,estimate_json:undefined}))});}
  const decisionMatch=path.match(/^\/officer\/claims\/([^/]+)\/decision$/);if(req.method==='POST'&&decisionMatch){const officer=requireUser(req,res,'officer');if(!officer)return;const {decision,note}=body;if(!['approved','rejected'].includes(decision)||!note)return json(res,400,{error:'decision (approved/rejected) and officer note are required'});const claim=one('SELECT * FROM claims WHERE id=?',decisionMatch[1]);if(!claim)return json(res,404,{error:'Claim not found'});run('UPDATE claims SET status=?,officer_id=?,officer_decision=?,officer_note=?,updated_at=? WHERE id=?',decision==='approved'?'approved':'rejected',officer.id,decision,note,now(),claim.id);audit(claim.id,officer.id,`coverage_${decision}`,note);return json(res,200,{message:`Coverage ${decision}`,claimId:claim.id,status:decision});}
  return json(res,404,{error:'Route not found'});
} catch(error) { console.error(error); return json(res,error.statusCode||500,{error:error.message||'Unexpected server error'}); } });
server.listen(PORT,()=>console.log(`InClaim API listening on http://localhost:${PORT}`));
